services:

  s3:
    image: localstack/localstack:s3-latest
    ports:
      - 4566:4566

  mongo:
    image: mongo:8.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - 4566:4566

  redis:
    image: redis:7.4.1-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - 6379:6379